#!/bin/bash
# lights daemon

DAEMON_PATH="/usr/local/src/lights"

DAEMON="forever"
DAEMONOPTS="src/server/app.js"

NAME=lights
DESC="Controlling telldus switches"
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME

case "$1" in
start)
    printf "%-50s" "Starting $NAME..."
    cd $DAEMON_PATH
    $DAEMON start $DAEMONOPTS
;;

stop)
    printf "%-50s" "Stopping $NAME"
    cd $DAEMON_PATH
    $DAEMON stop $DAEMONOPTS
;;

restart)
    $DAEMON restart $DAEMONOPTS
;;

*)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac