#!/bin/sh
#/etc/init.d/lights

DAEMON_PATH="/usr/local/src/lights"
PIDFILES="/tmp/forever"
SCRIPT="src/server/app.js"

export PATH=$PATH:/usr/local/bin
export NODE_PATH=$NODE_PATH:/usr/local/lib/node_modules

export NODE_ENV="production"
export PORT=8080

case "$1" in
  start)
  exec forever start --sourceDir=$DAEMON_PATH -p $PIDFILES $SCRIPT
  ;;
stop)
  exec forever stop --sourceDir=$DAEMON_PATH $SCRIPT
  ;;
restart)
  exec forever restart --sourceDir=$DAEMON_PATH -p $PIDFILES $SCRIPT
  ;;
*)
  echo "Usage: /etc/init.d/lights {start|stop|restart}"
  exit 1
  ;;
esac

exit 0